# Generated by Django 3.1.1 on 2020-12-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201218_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='hotOrCold',
            field=models.CharField(choices=[('Hot', 'Hot'), ('Cold', 'Cold')], max_length=64, null=True),
        ),
    ]
