# Generated by Django 3.1.1 on 2020-12-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_orderitem_hotorcold'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stay',
            field=models.CharField(choices=[('Stay', 'Stay'), ('Away', 'Away')], max_length=64, null=True),
        ),
    ]
