# Generated by Django 3.1.2 on 2021-01-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201227_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stay',
            field=models.CharField(choices=[('Stay', 'Stay'), ('Takeaway', 'Takeaway')], max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=set(),
        ),
    ]
