# Generated by Django 3.1.1 on 2021-02-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210128_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qrimg',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
