# Generated by Django 3.1.1 on 2021-02-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_order_qrimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='qrimg',
        ),
    ]
